#:schema ./config-schema.json

[mixer.inputs]
"ADAT 8" = { disabled = true }

[mixer.aux]
"Aux Phones" = { send = false }
"Aux JBL"    = { send = false }
"Aux Sub"    = { send = false }

[mixer.groups]
"Group 5" = { send = false, fader = false }
