#:schema ./config-schema.json

[mixer.inputs]
"ADAT 8" = { disabled = true }

[mixer.aux]
"Aux Phones" = { send = false }
"Aux JBL"    = { send = false }
"Aux Sub"    = { send = false }

[mixer.groups]
"Group 5" = { send = false, fader = false }

# [channel_strips]
# 0 = 2  # TR-8S Mix
# 1 = 4  # TR-8S Kick
# 2 = 5  # Sub-37
# 3 = 6  # Labyrinth
# 4 = 10 # Digitakt
# 5 = 12 # Minilogue XD
# 6 = 20 # FX Return
# 7 = 18 # Mac
