#:schema ./config-schema.json

[mixer.inputs]
"Post Master" = { disabled = true }

[mixer.aux]
"Aux 4"   = { send = false }
"Aux JBL" = { send = false }
"Aux Sub" = { send = false }

[mixer.groups]
"Group 5" = { send = false, fader = false }
