# Fader 1-8

[[channel_strip]]
src = "TR-8S"

[[channel_strip]]
src = "TR-8S Kick"

[[channel_strip]]
src = "Sub-37"

[[channel_strip]]
src = "Labyrinth"

[[channel_strip]]
src = "Digitakt"

[[channel_strip]]
src = "Pro-800"

[[channel_strip]]
src = "FX Return"

[[channel_strip]]
src = "Mac"

# Fader 9-16

[[channel_strip]]
src  = "TR-8S Group"
type = "group"

[[channel_strip]]
src  = "Analog Inputs"
type = "group"

[[channel_strip]]
src = "Minilogue XD"

[[channel_strip]]
src = "MS-20"

[[channel_strip]]
src = "Model D"
